### ISSUE TITLE
cannot get access to zotero list

### ISSUE THREAD

**Issue by jhpoelen** [tdwg/interaction#8]
hey y'all - tried to access reference list on zotero and found that I do not have access (see attached screenshot).

Is there a way to share the reference list in a more inclusive manner? 
![screenshot from 2017-07-18 11-18-18](https://user-images.githubusercontent.com/1084872/28332861-0969c874-6bab-11e7-9658-42a9402a0036.png)

**Comment by zedomel** [comment]
Hi @jhpoelen 
Can you try to access it now?
The Zotero group was closed to accept new memberships, now I change it to "Open group and Open Membership".
Any problem, please tell me.

Thanks.

**Comment by jhpoelen** [comment]
Thanks for your prompt reply. I tried again and . . . still not luck, same access denied error. Would it be easier to manage references in an openly accessible wiki page or text file?

**Comment by zedomel** [comment]
Really strange @jhpoelen. In this case, I agree with you. May be a simple text file or github wiki page will be enough to share the references list.
I set up these Zotero group because I think that will be easier to manage and import/export references. Has anyone experience the same issue, @saraiva-usp ? 
I also have removed and created the Zotero group again. Can you access https://www.zotero.org/groups/1554696/interaction_data ?
May be the URL is wrong at README.md file.
